namespace AAO.Apps.BCSCSelfAssessment.Controllers
{
    using System.Web.Mvc;

    [Authorize(Roles = "U")]
    public class BaseResidentController : BaseController
    {
        // GET: BaseResident
        // private string sAttrLogPath = ConfigurationManager.AppSettings.Get("LogfilePath");
        // protected override void OnActionExecuting(ActionExecutingContext filterContext)
        // {
        //    var userSession = Session["UserID"];
        //    if (userSession == null)
        //    {
        //        TempData["Msg"] = "Access denied !";
        //        filterContext.Result = new RedirectToRouteResult(
        //             new RouteValueDictionary
        //                 {{"controller", "Login"}, {"action", "SignOut"}});
        //        return;
        //    }

        // }
        // protected override void OnException(ExceptionContext filterContext)
        // {
        //    var log = new Serilog.LoggerConfiguration().WriteTo.RollingFile(this.sAttrLogPath, shared: true, retainedFileCountLimit: 7).CreateLogger();
        //    filterContext.Result = new RedirectToRouteResult(
        //            new RouteValueDictionary
        //                {{"controller", "Error"}, {"action", "Index"}});
        //    base.OnException(filterContext);
        //    var exception= filterContext.Exception;
        //    TempData["Msg"] = exception.Message.ToString();
        //    log.Information("Exception Message : " + filterContext.Exception);
        //    //log.Information("Error Generated by System/filterContext : " + filterContext.);
        //    filterContext.ExceptionHandled = true;
        // }
    }
}