namespace AAO.Apps.BCSCSelfAssessment.Controllers
{
    using System.Web.Mvc;

    [Authorize(Roles = "A")]
    public class BaseAdminController : BaseController
    {
        // GET: BaseAdmin
        // private string sAttrLogPath = ConfigurationManager.AppSettings.Get("LogfilePath");
        // protected override void OnActionExecuting(ActionExecutingContext filterContext)
        // {
        //    string userAgent;
        //    userAgent = Request.UserAgent;
        //    bool isMobile = Request.Browser.IsMobileDevice;
        //    // Check the user session
        //    var userSession = Session["UserID"];
        //    if (userSession == null)
        //    {
        //        TempData["Msg"] = "Access denied !";
        //        filterContext.Result = new RedirectToRouteResult(
        //             new RouteValueDictionary
        //                 {{"controller", "Login"}, {"action", "SignOut"}});
        //        return;
        //    }
        //    // Check the Mobile compatability
        //    if (isMobile)
        //    {
        //        TempData["Msg"] = "Access denied from Mobile devices ";
        //        filterContext.Result = new RedirectToRouteResult(
        //             new RouteValueDictionary
        //                 {{"controller", "Home"}, {"action", "Index"}});
        //        return;
        //    }
        // }
        // protected override void OnException(ExceptionContext filterContext)
        // {
        //    var log = new Serilog.LoggerConfiguration().WriteTo.RollingFile(this.sAttrLogPath, shared: true, retainedFileCountLimit: 7).CreateLogger();
        //    filterContext.Result = new RedirectToRouteResult(
        //            new RouteValueDictionary
        //                {{"controller", "Error"}, {"action", "Index"}});
        //    base.OnException(filterContext);
        //    var exception = filterContext.Exception;
        //    TempData["Msg"] = exception.Message.ToString();
        //    log.Information("Exception Message : " + filterContext.Exception);
        //    log.Information("Error Generated by System/filterContext : " + filterContext);
        //    filterContext.ExceptionHandled = true;
        // }
    }
}